### ISSUE TITLE
Corrupt files?

### ISSUE THREAD

**Issue by Wesver** [PokemonGoF/PokemonGo-Bot#2082]
My bot stopped working all of a sudden.
After logging in successfully, this is the message I keep getting in my terminal

**Anyone has a clue?**

Traceback (most recent call last):
  File "pokecli.py", line 494, in <module>
    main()
  File "pokecli.py", line 62, in main
    bot.start()
  File "/Users/User1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 54, in start
    self._setup_api()
  File "/Users/User1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 289, in _setup_api
    self.update_inventory()
  File "/Users/User1/PokemonGo-Bot/pokemongo_bot/__init__.py", line 397, in update_inventory
    if {"item_id", "count"}.issubset(set(item_info.keys())):
AttributeError: 'NoneType' object has no attribute 'keys'
PokeBot crashed with exit code 1.  Respawning..

**Comment by arnogues** [comment]
Same error here with latest code

Git commit : a7523a1ef9064e2470be69fb1a73a2bbbfa75373

**Comment by BlueHaunter** [comment]
Broken with #1587 at a7523a1

**Comment by BobbyWibowo** [comment]
Ah, an issue was submitted already. Yeah, got this as well.

**Comment by tansanrao** [comment]
just checked error occurs after the "refactor" commit. Commit eac7989d41cca4ee0289304f5b4b903e9ca4b6f3 is fine.

**Comment by douglascamata** [comment]
test latest dev now, I fixed.
