### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by p1n9** [PokemonGoF/PokemonGo-Bot#5405]
### Expected Behavior
Running fine

### Actual Behavior
Crash when try to run optimizer task

### config.json 
[http://pastebin.com/WegvkpMy](http://pastebin.com/WegvkpMy)

### Output when issue occurred
```
Traceback (most recent call last):
  File "pokecli.py", line 841, in <module>
    main()
  File "pokecli.py", line 200, in main
    bot.tick()
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/__init__.py", line 692, in tick
    if worker.work() == WorkerResult.RUNNING:
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 115, in work
    keep, try_evolve, try_upgrade = self.get_best_pokemon_for_rule(pokemon_list, rule)
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 242, in get_best_pokemon_for_rule
    sorted_pokemon = self.sort_pokemon_list_to_keep(pokemon_list, rule)
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 315, in sort_pokemon_list_to_keep
    scored_list = [(p, self.get_score(p, rule)) for p in pokemon_list]
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 337, in get_score
    may_try_evolve &= self.satisfy_requirements(pokemon, rule_evolve)
  File "/var/www/html/PokemonGo-Bot/pokemongo_bot/cell_workers/pokemon_optimizer.py", line 350, in satisfy_requirements
    for a, v in req.items():
AttributeError: 'list' object has no attribute 'items'
lundi 12 septembre 2016, 10:40:05 (UTC+0200) Pokebot  Stopped.
Press any button or wait 20 seconds to continue.
```

### Steps to Reproduce
Run the bot with optimizer task

### Other Information
OS: ubuntu 14.04
Branch: dev
Git Commit: 972fd53d969d8131de576a208621bce193ed99c7
Python Version: Python 2.7.6

**Comment by Anakin5** [comment]
This is wrong:
```
"evolve": [{"iv": 0.9}, {"ncp": "0.9"}],
"upgrade": [{"iv": 0.9}, {"ncp": "0.9"}]
```

should be

```
"evolve": {"iv": 0.9, "ncp": "0.9"},
"upgrade": {"iv": 0.9, "ncp": "0.9"}
```

**Comment by p1n9** [comment]
Wow !
Bad merge of my config file...
Didn't see it :(

Thanks to point me out !

**Comment by Anakin5** [comment]
;)
