### ISSUE TITLE
[DEV] Bot doesn't start since the last git pull

### ISSUE THREAD

**Issue by viruz82** [PokemonGoF/PokemonGo-Bot#1583]
### Expected Behavior
Bot should start

### Actual Behavior
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 24, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/opt/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/usr/local/lib/python2.7/dist-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/usr/local/lib/python2.7/dist-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: /usr/local/lib/python2.7/dist-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object

### Steps to Reproduce
python pokecli.py --config ./configs/config_01.json

### Other Information
new requirements have been installed with pip install -r requirements.txt
OS: Debian 7.11
Git Commit: a1433f235c0afc00a15d79ff99711c0cd520dc7f

**Comment by patitoaxel** [comment]
Did you try pip install -r requirements.txt --upgrade?

**Comment by markkvdb** [comment]
As stated in the error message. You have to install additional packages. Just run 
`$ source bin/activate`
`$ pip install -r requirements.txt`
again and everything should be fine.

**Comment by viruz82** [comment]
@patitoaxel 
Already done, doesn't help. :(

@markkvdb 
Done the provided steps and now I get this:

> Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pokemongo_bot import PokemonGoBot
  File "/opt/PokemonGo-Bot/pokemongo_bot/__init__.py", line 24, in <module>
    from pokemongo_bot.socketio_server.runner import SocketIoRunner
  File "/opt/PokemonGo-Bot/pokemongo_bot/socketio_server/runner.py", line 5, in <module>
    from eventlet import patcher, wsgi
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/patcher.py", line 4, in <module>
    from eventlet.support import six
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/__init__.py", line 4, in <module>
    from eventlet.support import greenlets, six
  File "/opt/PokemonGo-Bot/local/lib/python2.7/site-packages/eventlet/support/greenlets.py", line 3, in <module>
    import greenlet
ImportError: /opt/PokemonGo-Bot/local/lib/python2.7/site-packages/greenlet.so: undefined symbol: _PyTrash_thread_deposit_object
>

**Comment by Chrischi-** [comment]
do

virtualenv .
source bin/activate

and run python pokecli.py again.

**Comment by viruz82** [comment]
Same error...

**Comment by Chrischi-** [comment]
did you try all steps?

`$ virtualenv .
$ source bin/activate
$ pip install -r requirements.txt
$ git submodule init
$ git submodule update`

**Comment by lukaszraczylo** [comment]
It's caused by outdated python version ( via https://github.com/python-greenlet/greenlet/issues/24 ). You're probably on 2.7.3 ( as I am )

**Comment by viruz82** [comment]
@Chrischi-
When doing it again I get the following error:

> Obtaining pgoapi from git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi (from -r requirements.txt (line 1))
  Updating ./src/pgoapi clone (to 81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b)
  Could not find a tag or branch '81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b', assuming commit.
  Running setup.py egg_info for package pgoapi
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/opt/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>
        install_reqs = parse_requirements(path_req, session=False)
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/opt/PokemonGo-Bot/src/pgoapi/setup.py", line 9, in <module>

    install_reqs = parse_requirements(path_req, session=False)

TypeError: parse_requirements() got an unexpected keyword argument 'session'

> 

@lukaszraczylo
Yes, I'm on 2.7.3. This is the last stable release in my Debian 7.11.

**Comment by Leerzeichen** [comment]
On Ubuntu 12.04 this one solved the issue... Maybe also on Debian

sudo add-apt-repository ppa:fkrull/deadsnakes-python2.7
sudo apt-get update 
sudo apt-get install python2.7

From [here](http://superuser.com/questions/602587/how-to-use-latest-python-2-7-x-the-right-way-on-ubuntu-12-04-lts) (Last Answer)

**Comment by 1cu** [comment]
@viruz82 you just downgraded pip (`virtualenv .` did that). Upgrade it by running `easy_install -U pip`.
@lukaszraczylo can confirm. Bot stopped working on Debian 7.11 with Python 2.7.3 :-1:

**Comment by 1cu** [comment]
Fixed the issue on Debian 7.11, Python 2.7.3 by uninstalling greenlet (`pip uninstall greenlet`) and installing it via easy_install (`easy_install greenlet`).

**Comment by viruz82** [comment]
@1cu 
Thank you mate, that fixed it! :D

**Comment by LasseSkogland** [comment]
Close this issue, issue resolved.
